version: '3.7'
services:
  water:
    build: .
    image: water:latest
    ports:
      - '8888:8888'
    depends_on:
      - postgres
  postgres:
    image: postgres:10
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5438:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
